language: en
pipeline: supervised_embeddings
policies:
- max_history: 5
  name: MemoizationPolicy
- epochs: 200
  max_history: 5
  name: KerasPolicy
- fallback_action_name: action_default_fallback
  name: FallbackPolicy
- name: FormPolicy
